services:
  - type: web
    name: wecrypt-app
    runtime: docker
    plan: free
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: wecrypt-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: wecrypt-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: wecrypt-db
          property: database
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: wecrypt-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: wecrypt-db
          property: password
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update

databases:
  - name: wecrypt-db
    plan: free
    databaseName: kdc
