services:
  - type: web
    name: wecrypt-app
    runtime: docker
    plan: free
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: wecrypt-db
          property: jdbcConnectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: wecrypt-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: wecrypt-db
          property: password
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update

databases:
  - name: wecrypt-db
    plan: free
    databaseName: kdc
